# RRTPlanner:
visualize_potential: false
allow_unknown: true
planner_window_x: 0.0
planner_window_y: 0.0
default_tolerance: 0.1
step_size_: 0.25
delta_: 1.0
run_time_: 5
max_iterations_: 200000
goal_radius_: 1
controller_frequency: 0.5
